package com.partner.busi.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMatchUser<M extends BaseMatchUser<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Integer ID) {
		set("ID", ID);
	}

	public java.lang.Integer getID() {
		return get("ID");
	}

	public void setMatchId(java.lang.Integer matchId) {
		set("MATCH_ID", matchId);
	}

	public java.lang.Integer getMatchId() {
		return get("MATCH_ID");
	}

	public void setSEQ(java.lang.Integer SEQ) {
		set("SEQ", SEQ);
	}

	public java.lang.Integer getSEQ() {
		return get("SEQ");
	}

	public void setUserId(java.lang.Integer userId) {
		set("USER_ID", userId);
	}

	public java.lang.Integer getUserId() {
		return get("USER_ID");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("CREATE_TIME", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("CREATE_TIME");
	}

	public void setStartScore(java.lang.String startScore) {
		set("START_SCORE", startScore);
	}

	public java.lang.String getStartScore() {
		return get("START_SCORE");
	}

}
