package com.partner.busi.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseResetRec<M extends BaseResetRec<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Integer ID) {
		set("ID", ID);
	}

	public java.lang.Integer getID() {
		return get("ID");
	}

	public void setEMAIL(java.lang.String EMAIL) {
		set("EMAIL", EMAIL);
	}

	public java.lang.String getEMAIL() {
		return get("EMAIL");
	}

	public void setUUID(java.lang.String UUID) {
		set("UUID", UUID);
	}

	public java.lang.String getUUID() {
		return get("UUID");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("CREATE_TIME", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("CREATE_TIME");
	}

}
