package com.partner.busi.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIntroduce<M extends BaseIntroduce<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Integer ID) {
		set("ID", ID);
	}

	public java.lang.Integer getID() {
		return get("ID");
	}

	public void setTYPE(java.lang.Integer TYPE) {
		set("TYPE", TYPE);
	}

	public java.lang.Integer getTYPE() {
		return get("TYPE");
	}

	public void setCONTENT(java.lang.String CONTENT) {
		set("CONTENT", CONTENT);
	}

	public java.lang.String getCONTENT() {
		return get("CONTENT");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("CREATE_TIME", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("CREATE_TIME");
	}

	public void setCreateUserId(java.lang.Integer createUserId) {
		set("CREATE_USER_ID", createUserId);
	}

	public java.lang.Integer getCreateUserId() {
		return get("CREATE_USER_ID");
	}

}
