package com.partner.busi.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEvaluation<M extends BaseEvaluation<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Integer ID) {
		set("ID", ID);
	}

	public java.lang.Integer getID() {
		return get("ID");
	}

	public void setObjId(java.lang.Integer objId) {
		set("OBJ_ID", objId);
	}

	public java.lang.Integer getObjId() {
		return get("OBJ_ID");
	}

	public void setObjType(java.lang.Integer objType) {
		set("OBJ_TYPE", objType);
	}

	public java.lang.Integer getObjType() {
		return get("OBJ_TYPE");
	}

	public void setCONTENT(java.lang.String CONTENT) {
		set("CONTENT", CONTENT);
	}

	public java.lang.String getCONTENT() {
		return get("CONTENT");
	}

	public void setUserId(java.lang.Integer userId) {
		set("USER_ID", userId);
	}

	public java.lang.Integer getUserId() {
		return get("USER_ID");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("CREATE_TIME", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("CREATE_TIME");
	}

	public void setPId(java.lang.Integer pId) {
		set("P_ID", pId);
	}

	public java.lang.Integer getPId() {
		return get("P_ID");
	}

}
