package com.partner.busi.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysAccessLogHis<M extends BaseSysAccessLogHis<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Integer ID) {
		set("ID", ID);
	}

	public java.lang.Integer getID() {
		return get("ID");
	}

	public void setNum(java.lang.Integer num) {
		set("NUM", num);
	}

	public java.lang.Integer getNum() {
		return get("NUM");
	}

	public void setYYYYMM(java.lang.String YYYYMM) {
		set("YYYYMM", YYYYMM);
	}

	public java.lang.String getYYYYMM() {
		return get("YYYYMM");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("CREATE_TIME", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("CREATE_TIME");
	}

}
