package com.partner.busi.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseConfig<M extends BaseConfig<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Integer ID) {
		set("ID", ID);
	}

	public java.lang.Integer getID() {
		return get("ID");
	}

	public void setNAME(java.lang.String NAME) {
		set("NAME", NAME);
	}

	public java.lang.String getNAME() {
		return get("NAME");
	}

	public void setBusinessTime(java.lang.String businessTime) {
		set("BUSINESS_TIME", businessTime);
	}

	public java.lang.String getBusinessTime() {
		return get("BUSINESS_TIME");
	}

	public void setPHONE(java.lang.String PHONE) {
		set("PHONE", PHONE);
	}

	public java.lang.String getPHONE() {
		return get("PHONE");
	}

	public void setPlaceId(java.lang.String placeId) {
		set("PLACE_ID", placeId);
	}

	public java.lang.String getPlaceId() {
		return get("PLACE_ID");
	}

	public void setADDRESS(java.lang.String ADDRESS) {
		set("ADDRESS", ADDRESS);
	}

	public java.lang.String getADDRESS() {
		return get("ADDRESS");
	}

	public void setMapUrl(java.lang.String mapUrl) {
		set("MAP_URL", mapUrl);
	}

	public java.lang.String getMapUrl() {
		return get("MAP_URL");
	}

}
