package com.partner.busi.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseConfig<M extends BaseConfig<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Integer ID) {
		set("ID", ID);
	}

	public java.lang.Integer getID() {
		return get("ID");
	}

	public void setNAME(java.lang.String NAME) {
		set("NAME", NAME);
	}

	public java.lang.String getNAME() {
		return get("NAME");
	}

	public void setBusinessTime(java.lang.String businessTime) {
		set("BUSINESS_TIME", businessTime);
	}

	public java.lang.String getBusinessTime() {
		return get("BUSINESS_TIME");
	}

	public void setLONGITUDE(java.math.BigDecimal LONGITUDE) {
		set("LONGITUDE", LONGITUDE);
	}

	public java.math.BigDecimal getLONGITUDE() {
		return get("LONGITUDE");
	}

	public void setLATITUDE(java.math.BigDecimal LATITUDE) {
		set("LATITUDE", LATITUDE);
	}

	public java.math.BigDecimal getLATITUDE() {
		return get("LATITUDE");
	}

}
