package com.partner.busi.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("c_user", "ID", CUser.class);
		arp.addMapping("sys_access_log", "ID", SysAccessLog.class);
		arp.addMapping("sys_access_log_his", "ID", SysAccessLogHis.class);
		arp.addMapping("t_act_user", "ID", ActUser.class);
		arp.addMapping("t_activity", "ID", Activity.class);
		arp.addMapping("t_config", "ID", Config.class);
		arp.addMapping("t_contact", "ID", Contact.class);
		arp.addMapping("t_evaluation", "ID", Evaluation.class);
		arp.addMapping("t_game", "ID", Game.class);
		arp.addMapping("t_introduce", "ID", Introduce.class);
		arp.addMapping("t_match", "ID", Match.class);
		arp.addMapping("t_match_user", "ID", MatchUser.class);
		arp.addMapping("t_notice", "ID", Notice.class);
		arp.addMapping("t_picture", "ID", Picture.class);
		arp.addMapping("t_reset_rec", "ID", ResetRec.class);
		arp.addMapping("t_user", "ID", User.class);
	}
}

