package com.partner.busi.model;

import com.partner.busi.model.base.BaseActUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActUser extends BaseActUser<ActUser> {
	public static final ActUser dao = new ActUser();
}
