package com.partner.busi.model;

import com.partner.busi.model.base.BaseContact;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Contact extends BaseContact<Contact> {
	public static final Contact dao = new Contact();
}
