package com.partner.busi.model;

import com.partner.busi.model.base.BaseCUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CUser extends BaseCUser<CUser> {
	public static final CUser dao = new CUser();
	
	public CUser findByName(String name){
		 return dao.findFirst("select * from c_user where status = 0 and user_name = ?",name);
	}
}
