package com.partner.busi.model;

import com.partner.busi.model.base.BaseGame;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Game extends BaseGame<Game> {
	public static final Game dao = new Game();
}
