package com.partner.busi.model;

import com.jfinal.plugin.activerecord.Db;
import com.partner.busi.model.base.BaseGame;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Game extends BaseGame<Game> {
	public static final Game dao = new Game();
	
	/**
	 * 根据赛事ID删除所有比赛
	 * @param matchId
	 * @return
	 */
	public boolean deleteByMatchId(int matchId) {
		int rs = Db.update("delete from t_game where MATCH_ID = ?", matchId);
		if(rs==0){
			return false;
		}else{
			return true;
		}
	}
	
	/**
	 * 修改用户
	 * @param gameId
	 * @param userId
	 * @param userIndex
	 * @return
	 */
	public boolean updateUser(int gameId, Integer userId, int userIndex){
		int rs = Db.update("update t_game set USER"+userIndex+"=? where ID = ?", userId, gameId);
		return rs > 0;
	}
	
	/**
	 * 更新比分
	 * @param winId
	 * @param score1
	 * @param score2
	 * @return
	 */
	public boolean updateScore(int gameId, Integer winId, Integer score1, Integer score2){
		int rs = Db.update("update t_game set WINNER_ID=?, SCORE1=?, SCORE2=? where ID = ?", winId, score1, score2, gameId);
		return rs > 0;
	}
	
	/**
	 * 将用户移动到对应比赛
	 * @param matchId
	 * @param seq
	 * @param index
	 * @param userId
	 * @return
	 */
	public boolean moveUserToGame(int matchId, Integer seq, Integer index, Integer userId){
		int rs = Db.update("update t_game set USER" + index + "=? where MATCH_ID = ? and SEQ=?", userId, matchId, seq);
		return rs > 0;
	}

	public void setU1_SEQ(Long seq) {
		set("U1_SEQ", seq);
	}
	
	public Long getU1_SEQ() {
		return get("U1_SEQ");
	}
	
	public void setU2_SEQ(Long seq) {
		set("U2_SEQ", seq);
	}
	
	public Long getU2_SEQ() {
		return get("U2_SEQ");
	}
	
	public void setU1_NAME(String name) {
		set("U1_NAME", name);
	}
	
	public String getU1_NAME() {
		return get("U1_NAME");
	}
	
	public void setU2_NAME(String name) {
		set("U2_NAME", name);
	}
	
	public String getU2_NAME() {
		return get("U2_NAME");
	}
	
}
