package com.partner.busi.model;

import com.partner.busi.model.base.BaseIntroduce;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Introduce extends BaseIntroduce<Introduce> {
	public static final Introduce dao = new Introduce();
}
