package com.partner.busi.model;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.partner.busi.model.base.BaseMatchUser;
import org.apache.commons.lang.StringUtils;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Map;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MatchUser extends BaseMatchUser<MatchUser> {
	public static final MatchUser dao = new MatchUser();
	
	public List<MatchUser> findUserByMatchId(Map<String,Object> params){
		String sql = "select * from t_match_user where 1=1 ";
		List<Object> paraLst = new  ArrayList<Object>();
		if(StringUtils.isNotBlank((String) params.get("matchId"))){
			sql +=" AND MATCH_ID = ?  ";
			paraLst.add(params.get("matchId").toString());
		}
		if(StringUtils.isNotBlank((String) params.get("userId"))){
			sql +=" AND USER_ID = ? ";
			paraLst.add(params.get("userId").toString());
		}
		sql+=" ORDER BY CREATE_TIME ";
		return dao.find(sql,paraLst.toArray());
	};
	
	public void delMatchUser(int matchId, int userId){
		MatchUser user = dao.findFirst("select * from t_match_user where MATCH_ID = "+matchId+" AND USER_ID = "+userId);
		//user.set(attr, value);//修改状态，增加状态用来标记用户是否参加比赛
		dao.update();
	}
	
	public List<MatchUser> findMatchUserListBySeq(String matchId) {
		StringBuilder sql = new StringBuilder("select m.ID, u.NAME, m.START_SCORE, m.USER_ID, m.MATCH_ID from t_match_user m, t_user u where m.USER_ID = u.ID and m.SEQ IS NOT NULL AND m.MATCH_ID = "+matchId);
		/*List<Object> params = new ArrayList<Object>();
		params.add(matchId);*/
		sql.append(" order by m.SEQ");
		//return paginate(pageNum, pagesize, select, sql.toString(), params.toArray());
		return dao.find(sql.toString());
	}
	
	public MatchUser findMatchUserByUID(String matchId, String uid) {
		StringBuilder sql = new StringBuilder("select * from t_match_user where USER_ID = "+uid+" AND MATCH_ID = "+matchId);
		return dao.findFirst(sql.toString());
	}
	
	public List<MatchUser> findMatchUserListNoSeq(String matchId) {
		StringBuilder sql = new StringBuilder(" select m.ID, u.NAME, m.START_SCORE, m.USER_ID from t_match_user m, t_user u where m.USER_ID = u.ID and m.SEQ IS NULL AND m.MATCH_ID = "+matchId);
		sql.append(" order by m.SEQ ");
		return dao.find(sql.toString());
	}
	
	public List<MatchUser> findMatchUserListByMatchId(String matchId){
		StringBuilder sql = new StringBuilder(" select m.SEQ, m.CREATE_TIME, m.START_SCORE, u.EMAIL, u.GENDER, u.PHONE, u.NAME from t_match_user m, t_user u where m.USER_ID = u.ID AND m.MATCH_ID = "+matchId);
		sql.append(" order by m.SEQ ");
		return dao.find(sql.toString());
	}
	
	public Page<MatchUser> findMatchUserListByMatchId(int pageNum, Integer pagesize,String matchId){
		String select = " select m.SEQ, m.CREATE_TIME, m.START_SCORE, u.EMAIL, u.GENDER, u.PHONE, u.NAME";
		StringBuilder sql = new StringBuilder(" from t_match_user m, t_user u where m.USER_ID = u.ID AND m.MATCH_ID = "+matchId);
		sql.append(" order by m.CREATE_TIME ");
		return paginate(pageNum, pagesize, select, sql.toString());
	}
	
	public List<MatchUser> findUserByMatchId(int matchId){
		String sql = "select * from t_match_user where MATCH_ID = ? and SEQ is not null order by SEQ ";
		return dao.find(sql, matchId);
	};

	public boolean insertSecondMatchUser(Game game, int userId) {
		String sql = "insert into t_match_user(MATCH_ID, SEQ, USER_ID, CREATE_TIME, START_SCORE) values " +
				"(?, (select t.s + 1 from (select ifnull(max(seq), 0) as s from t_match_user where MATCH_ID=?) as t), ?, now(), (select LAST_START_SCORE from t_user where ID = ?))";
		int matchId = game.getMatchId();
		int rs = Db.update(sql, matchId, matchId, userId, userId);
		return rs > 0;
	}

	/**
	 * 用于双败转单败，删除上一轮同场比赛的两人
	 * @param game
	 * @param matchId
	 * @return
	 */
	public boolean deleteByGame(int matchId, Game game){
		String sql = "delete from t_match_user where match_id=? and (user_id = ? or user_id = ?)";
		int rs = Db.update(sql, matchId, game.getUSER1(), game.getUSER2());
		return rs > 0;
	}
	
	public void setNAME(String name) {
		set("NAME", name);
	}
	
	public String getNAME() {
		return get("NAME");
	}
	
	public void setEMAIL(String email) {
		set("EMAIL", email);
	}
	
	public String getEMAIL() {
		return get("EMAIL");
	}
	
	public void setGENDER(Integer gender) {
		set("GENDER", gender);
	}
	
	public Integer getGENDER() {
		return get("GENDER");
	}
	
	public void setPHONE(String phone) {
		set("PHONE", phone);
	}
	
	public String getPHONE() {
		return get("PHONE");
	}
	public void setMaxSeq(Integer maxSeq) {
		set("maxSeq", maxSeq);
	}
	
	public Integer getMaxSeq() {
		return get("maxSeq");
	}
	
	public String getCreateTimeStr() {
		Date startDate = this.getCreateTime();
		SimpleDateFormat formatDate = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
		return formatDate.format(startDate);
	}
	/**
	 * 
	 * @param matchId
	 * @param seq
	 * @return int >=1 为成功
	 * 批量对SEQ 进行递减操作
	 */
	public int batchUpdateSeq(int matchId, int seq){
		StringBuffer sb = new StringBuffer(" UPDATE t_match_user MU SET MU.SEQ = MU.SEQ-1 WHERE MU.MATCH_ID = "+matchId+" AND MU.SEQ IS NOT NULL AND MU.SEQ > "+seq);
		return Db.update(sb.toString());
	}
	
	/**
	 * 
	 * @param matchId
	 * @param start 更新区间的开始值
	 * @param end  更新区间的开始值
	 * @return int 返回更新的记录数
	 * 指间区间批量对SEQ 进行递减操作
	 */
	public int batchUpdateSeqSub(int matchId, int start, int end){
		start = start+1;
		end =end+2;
		StringBuffer sb = new StringBuffer(" UPDATE t_match_user MU SET MU.SEQ = MU.SEQ-1 WHERE MU.MATCH_ID = "+matchId+" AND MU.SEQ IS NOT NULL AND MU.SEQ > "+start+" AND MU.SEQ < "+end);
		return Db.update(sb.toString());
	}
	
	public int batchUpdateSeqAdd(int matchId, int start, int end){
		end =end+1;
		StringBuffer sb = new StringBuffer(" UPDATE t_match_user MU SET MU.SEQ = MU.SEQ+1 WHERE MU.MATCH_ID = "+matchId+" AND MU.SEQ IS NOT NULL AND MU.SEQ > "+start+" AND MU.SEQ < "+end);
		return Db.update(sb.toString());
	}
	
	public int countMatchPersion(int matchId){
		String sql = " SELECT max(seq) as maxSeq  from t_match_user where MATCH_ID = "+matchId+" and SEQ IS NOT NULL";
		MatchUser matchUser = dao.findFirst(sql);
		if(matchUser.getMaxSeq() == null)
			return 0;
		else
		return matchUser.getMaxSeq();
	}
	
	public boolean deleteByUserIdAndActId(Integer userId, int matId) {
		int rs = Db.update("delete from t_match_user where USER_ID = ? and MATCH_ID = ?",userId,matId);
		if(rs==0){
			return false;
		}else{
			return true;
		}
	}
	/**
	 * 
	 * @param id
	 * @param score
	 * @return int >=1 为成功
	 */
	public int updateStartScore(int id, String score){
		StringBuffer sb = new StringBuffer(" UPDATE t_match_user MU SET MU.START_SCORE = '"+score+"' WHERE MU.ID = "+id);
		return Db.update(sb.toString());
	}

	public Page<MatchUser> findMatUserList(String title, int pageNum, int pageSize) {
		String select = " select t.* ";
		StringBuilder sql = new StringBuilder(" FROM t_user t where t.LAST_START_SCORE<>'' ");
		List<Object> params = new ArrayList<Object>();
		if (StringUtils.isNotBlank(title)) {
			sql.append(" and NAME like ? ");
			params.add("%" + title + "%");
		}
		sql.append(" ORDER BY t.NICKNAME ");
		return paginate(pageNum, pageSize, select, sql.toString(), params.toArray());
	}
}
