package com.partner.busi.model;

import com.partner.busi.model.base.BaseMatchUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MatchUser extends BaseMatchUser<MatchUser> {
	public static final MatchUser dao = new MatchUser();
}
