package com.partner.busi.model;

import com.partner.busi.model.base.BasePicture;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Picture extends BasePicture<Picture> {
	public static final Picture dao = new Picture();
}
