package com.partner.busi.model;

import java.util.List;

import com.partner.busi.model.base.BasePicture;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Picture extends BasePicture<Picture> {
	public static final Picture dao = new Picture();
	
	public List<Picture> findAll(){
		return dao.find("select URL, DESCRIPTION, USER_ID from t_picture order by CREATE_TIME desc ");
	}
}
