package com.partner.busi.model;

import com.partner.busi.model.base.BaseResetRec;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ResetRec extends BaseResetRec<ResetRec> {
	public static final ResetRec dao = new ResetRec();
}
