package com.partner.busi.model;

import com.partner.busi.model.base.BaseSysAccessLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysAccessLog extends BaseSysAccessLog<SysAccessLog> {
	public static final SysAccessLog dao = new SysAccessLog();
}
