package com.partner.busi.model;

import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;

import org.apache.commons.lang.StringUtils;

import com.jfinal.plugin.activerecord.Db;
import com.partner.busi.model.base.BaseSysAccessLog;
import com.partner.busi.model.base.BaseSysAccessLogHis;
import com.partner.common.util.DateUtil;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysAccessLogHis extends BaseSysAccessLogHis<SysAccessLogHis> {
	public static final SysAccessLogHis dao = new SysAccessLogHis();
	
	public Long countTotal(){
		Long rs = Long.parseLong(Db.queryBigDecimal("select SUM(NUM) from sys_access_log_his ").toString());
		return rs;
	}
}
